"""Provider catalog: install guides, presets, secret names — UI-driven setup."""

from __future__ import annotations

from typing import Any

PROVIDER_CATALOG: list[dict[str, Any]] = [
    {
        "id": "demo",
        "name": "Demo",
        "tagline": "Works instantly — no install",
        "difficulty": "easiest",
        "cost": "Free",
        "needs_api_key": False,
        "needs_install": False,
        "default_base_url": None,
        "secret_name": None,
        "install": {
            "title": "Already built in",
            "steps": [
                "Select Demo and click Activate — nothing to download.",
                "Upgrade later to Ollama (local) or a cloud provider for richer chat.",
            ],
            "links": [],
        },
        "presets": [
            {"id": "demo", "label": "Demo agent", "model": "demo", "tier": "instant", "ram": "—"},
        ],
    },
    {
        "id": "ollama",
        "name": "Ollama (Local)",
        "tagline": "Free private AI on your PC",
        "difficulty": "easy",
        "cost": "Free",
        "needs_api_key": False,
        "needs_install": True,
        "default_base_url": "http://127.0.0.1:11434",
        "secret_name": None,
        "recommended_for": "finance",
        "install": {
            "title": "Install Ollama in 2 minutes",
            "steps": [
                "Download and install Ollama for your OS (Windows / Mac / Linux).",
                "Click any preset below — FinAgent downloads and activates it (3B → 405B).",
                "Match model size to your RAM/VRAM (see each card). Prices still come from FinAgent tools.",
            ],
            "links": [
                {"label": "Download Ollama", "url": "https://ollama.com/download"},
                {"label": "Model library", "url": "https://ollama.com/library"},
                {
                    "label": "Plutus (finance fine-tune)",
                    "url": "https://ollama.com/0xroyce/plutus",
                },
            ],
        },
        "presets": [
            # --- Fast / low RAM ---
            {
                "id": "qwen25-3b",
                "label": "Qwen2.5 3B",
                "model": "qwen2.5:3b",
                "tier": "fast",
                "ram": "4–8 GB",
                "pull": "qwen2.5:3b",
                "note": "CPU-friendly starter. Weak for free-form chat — tools still work.",
            },
            {
                "id": "llama32-3b",
                "label": "Llama 3.2 3B",
                "model": "llama3.2:3b",
                "tier": "fast",
                "ram": "4–8 GB",
                "pull": "llama3.2:3b",
            },
            # --- Balanced (laptop / 8–16 GB) ---
            {
                "id": "qwen25-7b",
                "label": "Qwen2.5 7B (recommended)",
                "model": "qwen2.5:7b",
                "tier": "balanced",
                "ram": "8–16 GB",
                "pull": "qwen2.5:7b",
                "recommended_for": "finance",
                "note": "Best first local model for most PCs.",
            },
            {
                "id": "llama31-8b",
                "label": "Llama 3.1 8B",
                "model": "llama3.1:8b",
                "tier": "balanced",
                "ram": "8–16 GB",
                "pull": "llama3.1:8b",
                "recommended_for": "finance",
            },
            {
                "id": "mistral-7b",
                "label": "Mistral 7B",
                "model": "mistral:7b",
                "tier": "balanced",
                "ram": "8–16 GB",
                "pull": "mistral:7b",
            },
            {
                "id": "deepseek-r1-8b",
                "label": "DeepSeek-R1 8B (reasoning)",
                "model": "deepseek-r1:8b",
                "tier": "balanced",
                "ram": "8–16 GB",
                "pull": "deepseek-r1:8b",
                "note": "Stronger chain-of-thought; slower than plain 7–8B.",
            },
            {
                "id": "plutus",
                "label": "Plutus (finance fine-tune)",
                "model": "0xroyce/plutus",
                "tier": "finance",
                "ram": "8–16 GB",
                "pull": "0xroyce/plutus",
                "recommended_for": "finance",
                "note": "Llama 3.1 8B finance fine-tune. Verify prices via tools.",
            },
            {
                "id": "adaptllm-finance",
                "label": "AdaptLLM finance-chat 7B",
                "model": "hf.co/TheBloke/finance-chat-GGUF",
                "tier": "finance",
                "ram": "8–16 GB",
                "pull": "hf.co/TheBloke/finance-chat-GGUF",
                "recommended_for": "finance",
                "note": "Community GGUF — may need Ollama HF support.",
            },
            # --- Mid / high (12–24 GB GPU) ---
            {
                "id": "qwen25-14b",
                "label": "Qwen2.5 14B",
                "model": "qwen2.5:14b",
                "tier": "quality",
                "ram": "12–24 GB",
                "pull": "qwen2.5:14b",
                "recommended_for": "finance",
                "note": "Clear step up from 7–8B. ~9 GB download.",
            },
            {
                "id": "deepseek-r1-14b",
                "label": "DeepSeek-R1 14B (reasoning)",
                "model": "deepseek-r1:14b",
                "tier": "quality",
                "ram": "12–24 GB",
                "pull": "deepseek-r1:14b",
            },
            {
                "id": "phi4-14b",
                "label": "Phi-4 14B",
                "model": "phi4:14b",
                "tier": "quality",
                "ram": "12–24 GB",
                "pull": "phi4:14b",
            },
            {
                "id": "gemma3-12b",
                "label": "Gemma 3 12B",
                "model": "gemma3:12b",
                "tier": "quality",
                "ram": "12–24 GB",
                "pull": "gemma3:12b",
            },
            {
                "id": "mistral-small-24b",
                "label": "Mistral Small 24B",
                "model": "mistral-small:24b",
                "tier": "quality",
                "ram": "16–32 GB",
                "pull": "mistral-small:24b",
            },
            {
                "id": "gemma3-27b",
                "label": "Gemma 3 27B",
                "model": "gemma3:27b",
                "tier": "quality",
                "ram": "24 GB+",
                "pull": "gemma3:27b",
            },
            # --- High-end (24 GB+ / workstation) ---
            {
                "id": "qwen25-32b",
                "label": "Qwen2.5 32B (high-end)",
                "model": "qwen2.5:32b",
                "tier": "high-end",
                "ram": "24–48 GB",
                "pull": "qwen2.5:32b",
                "recommended_for": "finance",
                "note": "Best quality-per-GB locally. ~20 GB VRAM at Q4.",
            },
            {
                "id": "qwen25-coder-32b",
                "label": "Qwen2.5 Coder 32B",
                "model": "qwen2.5-coder:32b",
                "tier": "high-end",
                "ram": "24–48 GB",
                "pull": "qwen2.5-coder:32b",
                "note": "Strong for structured tool JSON / analysis scripts.",
            },
            {
                "id": "deepseek-r1-32b",
                "label": "DeepSeek-R1 32B (reasoning)",
                "model": "deepseek-r1:32b",
                "tier": "high-end",
                "ram": "24–48 GB",
                "pull": "deepseek-r1:32b",
                "recommended_for": "finance",
                "note": "Top open reasoning mid-size for multi-step finance Q&A.",
            },
            {
                "id": "mixtral-8x7b",
                "label": "Mixtral 8×7B (MoE)",
                "model": "mixtral:8x7b",
                "tier": "high-end",
                "ram": "24–48 GB",
                "pull": "mixtral:8x7b",
            },
            # --- Flagship (48 GB+ / multi-GPU) ---
            {
                "id": "llama33-70b",
                "label": "Llama 3.3 70B (flagship)",
                "model": "llama3.3:70b",
                "tier": "flagship",
                "ram": "48 GB+ VRAM / unified",
                "pull": "llama3.3:70b",
                "recommended_for": "finance",
                "note": "Top open general model. ~40 GB download — needs serious hardware.",
            },
            {
                "id": "llama31-70b",
                "label": "Llama 3.1 70B",
                "model": "llama3.1:70b",
                "tier": "flagship",
                "ram": "48 GB+ VRAM / unified",
                "pull": "llama3.1:70b",
            },
            {
                "id": "qwen25-72b",
                "label": "Qwen2.5 72B (flagship)",
                "model": "qwen2.5:72b",
                "tier": "flagship",
                "ram": "48 GB+ VRAM / unified",
                "pull": "qwen2.5:72b",
                "recommended_for": "finance",
            },
            {
                "id": "deepseek-r1-70b",
                "label": "DeepSeek-R1 70B (reasoning)",
                "model": "deepseek-r1:70b",
                "tier": "flagship",
                "ram": "48 GB+ VRAM / unified",
                "pull": "deepseek-r1:70b",
            },
            {
                "id": "llama31-405b",
                "label": "Llama 3.1 405B (extreme)",
                "model": "llama3.1:405b",
                "tier": "flagship",
                "ram": "Multi-GPU / 200 GB+",
                "pull": "llama3.1:405b",
                "note": "Datacenter-class. Most home PCs cannot run this.",
            },
        ],
    },
    {
        "id": "openai",
        "name": "OpenAI",
        "tagline": "GPT-4o / GPT-4.1 / o-series",
        "difficulty": "easy",
        "cost": "Pay per use",
        "needs_api_key": True,
        "needs_install": False,
        "default_base_url": "https://api.openai.com/v1",
        "secret_name": "OPENAI_API_KEY",
        "recommended_for": "finance",
        "install": {
            "title": "Connect OpenAI",
            "steps": [
                "Create an API key at platform.openai.com → API keys.",
                "Paste the key below (stored encrypted on your server).",
                "Pick a model preset → Test → Activate.",
            ],
            "links": [
                {"label": "Get API key", "url": "https://platform.openai.com/api-keys"},
            ],
        },
        "presets": [
            {
                "id": "gpt4o-mini",
                "label": "GPT-4o mini (cheap & fast)",
                "model": "gpt-4o-mini",
                "tier": "fast",
                "ram": "cloud",
                "recommended_for": "finance",
            },
            {
                "id": "gpt4o",
                "label": "GPT-4o",
                "model": "gpt-4o",
                "tier": "quality",
                "ram": "cloud",
                "recommended_for": "finance",
            },
            {
                "id": "gpt41",
                "label": "GPT-4.1 (high-end)",
                "model": "gpt-4.1",
                "tier": "high-end",
                "ram": "cloud",
                "recommended_for": "finance",
            },
            {
                "id": "gpt41-mini",
                "label": "GPT-4.1 mini",
                "model": "gpt-4.1-mini",
                "tier": "balanced",
                "ram": "cloud",
            },
            {
                "id": "o4-mini",
                "label": "o4-mini (reasoning)",
                "model": "o4-mini",
                "tier": "high-end",
                "ram": "cloud",
                "recommended_for": "finance",
            },
            {
                "id": "o3",
                "label": "o3 (flagship reasoning)",
                "model": "o3",
                "tier": "flagship",
                "ram": "cloud",
                "note": "Highest OpenAI reasoning tier — check account access.",
            },
        ],
    },
    {
        "id": "anthropic",
        "name": "Anthropic",
        "tagline": "Claude Haiku / Sonnet / Opus",
        "difficulty": "easy",
        "cost": "Pay per use",
        "needs_api_key": True,
        "needs_install": False,
        "default_base_url": "https://api.anthropic.com",
        "secret_name": "ANTHROPIC_API_KEY",
        "recommended_for": "finance",
        "install": {
            "title": "Connect Anthropic",
            "steps": [
                "Create an API key at console.anthropic.com.",
                "Paste the key below → pick Claude → Test → Activate.",
            ],
            "links": [
                {"label": "Get API key", "url": "https://console.anthropic.com/settings/keys"},
            ],
        },
        "presets": [
            {
                "id": "claude-haiku",
                "label": "Claude 3.5 Haiku (fast)",
                "model": "claude-3-5-haiku-latest",
                "tier": "fast",
                "ram": "cloud",
            },
            {
                "id": "claude-sonnet",
                "label": "Claude Sonnet 4 (quality)",
                "model": "claude-sonnet-4-20250514",
                "tier": "quality",
                "ram": "cloud",
                "recommended_for": "finance",
            },
            {
                "id": "claude-opus",
                "label": "Claude Opus 4 (flagship)",
                "model": "claude-opus-4-20250514",
                "tier": "flagship",
                "ram": "cloud",
                "recommended_for": "finance",
                "note": "Highest Claude tier for deep analysis.",
            },
        ],
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "tagline": "One key → many models",
        "difficulty": "easy",
        "cost": "Pay per use",
        "needs_api_key": True,
        "needs_install": False,
        "default_base_url": "https://openrouter.ai/api/v1",
        "secret_name": "OPENROUTER_API_KEY",
        "install": {
            "title": "Connect OpenRouter",
            "steps": [
                "Sign up at openrouter.ai and create a key.",
                "Paste the key → choose any model id → Test → Activate.",
            ],
            "links": [
                {"label": "Get API key", "url": "https://openrouter.ai/keys"},
                {"label": "Browse models", "url": "https://openrouter.ai/models"},
            ],
        },
        "presets": [
            {
                "id": "or-gemini-flash",
                "label": "Google Gemini Flash",
                "model": "google/gemini-2.0-flash-001",
                "tier": "fast",
                "ram": "cloud",
            },
            {
                "id": "or-gemini-pro",
                "label": "Google Gemini 2.5 Pro",
                "model": "google/gemini-2.5-pro-preview",
                "tier": "flagship",
                "ram": "cloud",
                "recommended_for": "finance",
            },
            {
                "id": "or-deepseek",
                "label": "DeepSeek Chat",
                "model": "deepseek/deepseek-chat",
                "tier": "balanced",
                "ram": "cloud",
            },
            {
                "id": "or-deepseek-r1",
                "label": "DeepSeek R1 (reasoning)",
                "model": "deepseek/deepseek-r1",
                "tier": "high-end",
                "ram": "cloud",
                "recommended_for": "finance",
            },
            {
                "id": "or-llama70",
                "label": "Llama 3.3 70B",
                "model": "meta-llama/llama-3.3-70b-instruct",
                "tier": "high-end",
                "ram": "cloud",
            },
            {
                "id": "or-qwen72",
                "label": "Qwen2.5 72B",
                "model": "qwen/qwen-2.5-72b-instruct",
                "tier": "high-end",
                "ram": "cloud",
            },
        ],
    },
    {
        "id": "groq",
        "name": "Groq",
        "tagline": "Very fast cloud inference",
        "difficulty": "easy",
        "cost": "Free tier / pay",
        "needs_api_key": True,
        "needs_install": False,
        "default_base_url": "https://api.groq.com/openai/v1",
        "secret_name": "GROQ_API_KEY",
        "install": {
            "title": "Connect Groq",
            "steps": [
                "Create a key at console.groq.com.",
                "Paste the key → pick a model → Test → Activate.",
            ],
            "links": [{"label": "Get API key", "url": "https://console.groq.com/keys"}],
        },
        "presets": [
            {
                "id": "groq-llama",
                "label": "Llama 3.3 70B (Groq)",
                "model": "llama-3.3-70b-versatile",
                "tier": "high-end",
                "ram": "cloud",
                "recommended_for": "finance",
            },
            {
                "id": "groq-70b-spec",
                "label": "Llama 3.1 70B",
                "model": "llama-3.1-70b-versatile",
                "tier": "high-end",
                "ram": "cloud",
            },
            {
                "id": "groq-r1",
                "label": "DeepSeek-R1 Distill Llama 70B",
                "model": "deepseek-r1-distill-llama-70b",
                "tier": "flagship",
                "ram": "cloud",
            },
            {
                "id": "groq-8b",
                "label": "Llama 3.1 8B Instant",
                "model": "llama-3.1-8b-instant",
                "tier": "fast",
                "ram": "cloud",
            },
        ],
    },
    {
        "id": "openai-compatible",
        "name": "Custom / LM Studio",
        "tagline": "Any OpenAI-compatible endpoint",
        "difficulty": "advanced",
        "cost": "Yours",
        "needs_api_key": False,
        "needs_install": True,
        "default_base_url": "http://127.0.0.1:1234/v1",
        "secret_name": "OPENAI_API_KEY",
        "install": {
            "title": "Point at your server",
            "steps": [
                "Start LM Studio / vLLM / LocalAI with an OpenAI-compatible API.",
                "Enter the Base URL (usually ends with /v1).",
                "Enter the model id your server expects → Test → Activate.",
            ],
            "links": [
                {"label": "LM Studio", "url": "https://lmstudio.ai/"},
            ],
        },
        "presets": [
            {
                "id": "lmstudio-local",
                "label": "LM Studio default",
                "model": "local-model",
                "tier": "custom",
                "ram": "your PC",
            },
        ],
    },
]


def get_catalog() -> list[dict[str, Any]]:
    return PROVIDER_CATALOG


def get_provider(provider_id: str) -> dict[str, Any] | None:
    for p in PROVIDER_CATALOG:
        if p["id"] == provider_id:
            return p
    return None
