"""Auto-create .env with secure secrets so users never edit config files."""

from __future__ import annotations

import secrets
from pathlib import Path

from cryptography.fernet import Fernet


def ensure_runtime_env(project_root: Path | None = None) -> Path:
    """Create `.env` with generated secrets if missing. Returns path used."""
    root = project_root or Path.cwd()
    env_path = root / ".env"
    if env_path.exists():
        return env_path

    fernet = Fernet.generate_key().decode()
    jwt = secrets.token_urlsafe(48)
    content = f"""# Auto-generated by FinAgent — no need to edit
FINAGENT_HOST=0.0.0.0
FINAGENT_PORT=8000
FINAGENT_DATA_DIR=./data
FINAGENT_DATABASE_URL=sqlite+aiosqlite:///finagent.db
FINAGENT_SECRET_KEY={fernet}
FINAGENT_JWT_SECRET={jwt}
"""
    env_path.write_text(content, encoding="utf-8")
    (root / "data").mkdir(parents=True, exist_ok=True)
    return env_path
